### ISSUE TITLE
Call method

### ISSUE THREAD

**Issue by reef1390** [ZoobiDoobi/shopify_codeigniter_working_example#1]
How to PUT or GET product list using call function?

**Comment by awebartisan** [comment]
Consult the documentation here...
[Original Wrapper Code and Docs](https://github.com/joshrps/laravel-shopify-API-wrapper)
Best of luck :)

**Comment by javaidTa** [comment]
the documentation you have mentioned as for laravel not for codeigniter

**Comment by ZoobiDoobi** [comment]
Closing as its too old.
