### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by reef1390** [ZoobiDoobi/shopify_codeigniter_working_example#2]
Fatal error: Access to undeclared static property: Shopify::$_KEYS in 
application\libraries\Shopify.php on line 152

when access 

```
$shop = $this->session->userdata('shop');
	    $access_token =  $this->session->userdata('access_token');
	    $data = array(
            'API_KEY' => $this->config->item('shopify_api_key'),
            'API_SECRET' => $this->config->item('shopify_secret'),
            'SHOP_DOMAIN' => $shop,
            'ACCESS_TOKEN' => $access_token
        );
            $this->load->library('Shopify' , $data); 
	    
	     $result = $this->shopify->call([ 
							        'METHOD'    => 'GET', 
							        'URL'       => '/admin/products.json?page=1' 
							    ]); 
							    $products = $result->products; 
			
```
Thanks

**Comment by awebartisan** [comment]
Hi, thanks for opening this issue... few things you should know, the wrapper I am using which is basically meant for Laravel. I have modified it a little bit to work with CodeIgniter.
[Original Wrapper Link](https://github.com/joshrps/laravel-shopify-API-wrapper/blob/master/src/RocketCode/Shopify/API.php)
Now, the reason you are seeing this error is the `self::` keyword and operator at
[this line](https://github.com/ZoobiDoobi/shopify_codeigniter_working_example/blob/master/application/libraries/Shopify.php#L149)
Change it to `$this->_KEYS` and it should work then.

**Comment by tarunm60** [comment]
Hi
I have found Fatal error: Call to a member function getAccessToken() on null in /home/admin/web/domain_name/public_html/cookiebar/application/controllers/Auth.php on line 80 when I am installing this app.
