### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by tarunm60** [ZoobiDoobi/shopify_codeigniter_working_example#4]
Hi
I have found Fatal error: 

> Call to a member function getAccessToken() on null in /home/admin/web/domain_name/public_html/cookiebar/application/controllers/Auth.php on line 80 

when I am installing this app.

When I load the Shopify library then it's showing me following error:

>  An uncaught Exception was encountered
> 
>     Type: Exception
> 
>     Message: ERROR #22: The requested URL returned error: 400 Bad Request
> 
>     Filename: /home/admin/web/domain_name/public_html/cookiebar/application/libraries/Shopify.php
>

**Comment by awebartisan** [comment]
When you try to install app, and an error occurs, the 'code' in callback url is expired. You need to uninstall it from your shop and also remove the shop data from your database, then try to reinstall it by including Shopify library, because your first error is because of not including Shopify library. 

Hope it helps. Thanks!

**Comment by tarunm60** [comment]
So there is no needs to change in the following function for first time installing:

```
public function authCallback(){
    	
        $code = $this->input->get('code');
        $shop = $this->input->get('shop');

        if(isset($code)){
        	
            $data = array(
            
	            'API_KEY' => $this->config->item('shopify_api_key'),
	            'API_SECRET' => $this->config->item('shopify_secret'),
	            'SHOP_DOMAIN' => $shop,
	            'ACCESS_TOKEN' => ''
	        );
			
            $this->load->library('Shopify' , $data); //load shopify library and pass values in constructor
        }
		
        $accessToken = $this->shopify->getAccessToken($code);
		
        $this->session->set_userdata(['shop' => $shop , 'access_token' => $accessToken]);
		
        redirect('https://'.$shop.'/admin/apps');
    }
```

**Comment by awebartisan** [comment]
`$this->load->library('shopify' , $data); //load shopify library and pass values in constructor`
You may need to change library name to small , (codeigniter conventions)
Otherwise, this looks good to me.

Let me know if you need further help.

**Comment by tarunm60** [comment]
But if code is not set then it will got the $accessToken = $this->shopify->getAccessToken($code); but then it will showing the error of Undefined index: API_KEY, API_SECRET, SHOP_DOMAIN because of the library is not loaded.

**Comment by awebartisan** [comment]
Ah yes! Now I have got your point, actually I haven't used it for a long time and I have moved to Laravel, you can move everything within that `if` statement. sure.

**Comment by tarunm60** [comment]
Like this:
public function authCallback(){
    	
        $code = $this->input->get('code');
        $shop = $this->input->get('shop');

        if(isset($code)){
        	
            $data = array(
            
	            'API_KEY' => $this->config->item('shopify_api_key'),
	            'API_SECRET' => $this->config->item('shopify_secret'),
	            'SHOP_DOMAIN' => $shop,
	            'ACCESS_TOKEN' => ''
	        );
			
            $this->load->library('Shopify' , $data); //load shopify library and pass values in constructor
            
            $accessToken = $this->shopify->getAccessToken($code);
		
        	$this->session->set_userdata(['shop' => $shop , 'access_token' => $accessToken]);
		
        	redirect('https://'.$shop.'/admin/apps');
        }
    }
```

**Comment by awebartisan** [comment]
Yes!, have you tested this code?
let me know if you still facing any issue.

**Comment by tarunm60** [comment]
Now which url Needs to add in app URls

App URL:

Whitelisted redirection URL(s):

**Comment by awebartisan** [comment]
Contact me with on my email or give me your skype so I can help you setup things.

**Comment by tarunm60** [comment]
tarun_wedo

**Comment by tarunm60** [comment]
The App is working now thanks for your kind support.
