### ISSUE TITLE
Issue with creating product!

### ISSUE THREAD

**Issue by javaidTa** [ZoobiDoobi/shopify_codeigniter_working_example#5]
I am using this code in my app i have successfully integrated it. i can get access token e.t.c clearly now i need to create a product so i am stuck that how i will call the library to post product to shopify using access token, api key and api secret, shop domain.

can you please quide me that how i will call post product just like getaccesstoken 

your help will be appreciated!

Thanks!

**Comment by awebartisan** [comment]
Hello there, 
`       
           $shop = $this->session->userdata('shop_domain');
            $accessToken = $this->session->userdata('access_token');
            $shop_id = $this->session->userdata('shop_id');


        $lib_data = array(
            'API_KEY' => $this->config->item('shopify_api_key'),
            'API_SECRET' => $this->config->item('shopify_secret'),
            'SHOP_DOMAIN' => $shop,
            'ACCESS_TOKEN' => $accessToken
        );

        $this->load->library('shopify', $lib_data);
        $args = array(
            'URL' => '/admin/products.json',
            'METHOD' => 'POST',
            'RETURNARRAY' => TRUE,
            'DATA' => array('product' => array('name' => 'Awesome Product'))
        );
        try {
            $response = $this->shopify->call($args);
        } catch (Exception $e) {
            $response = $e->getMessage();
            log_message('error', 'In Product create function ' . $response);
            redirect('/wrong/index');
        }`

If you need more help, contact me at **awebartisan@gmail.com**
