### ISSUE TITLE
App Redirection Issue

### ISSUE THREAD

**Issue by shindevishal40** [ZoobiDoobi/shopify_codeigniter_working_example#7]
Hi ,
I created an app using the code and it works perfectly. Thanks for it.
The only problem I am having is once I open my store and go on the app listing page I click on the app link. It redirects me to the same app listing page instead of the embedded app.
Now I have to again click on the same link and then the embedded app opens.

Can you please check and let me know why this would be happening?

Other apps in the listing are working properly ( 3rd party apps).

**Comment by awebartisan** [comment]
Hi, are the settings correct? embedded app sdk initialization is correct in javascript?

**Comment by shindevishal40** [comment]
Hi ,
The redirect url needed to be updated now. Its now working perfectly. Thanks for your help.

**Comment by awebartisan** [comment]
Great. I highly recommend using Laravel for Shopify App Development because its projects are maintained properly.
